<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Garantiza la existencia del catálogo maosa_internal.cat_usuarios_importado,
 * consumido por el select de estaciones en la gestión de usuarios.
 *
 * En Producción la tabla ya existe (la mantiene el proceso de importación),
 * por lo que todas las sentencias usan IF NOT EXISTS y la migración es idempotente.
 * En Desarrollo crea el schema y la tabla con la estructura mínima requerida.
 */
return new class extends Migration
{
    public function up(): void
    {
        if (DB::getDriverName() !== 'pgsql') {
            return;
        }

        DB::statement('CREATE SCHEMA IF NOT EXISTS maosa_internal');

        DB::statement(<<<'SQL'
            CREATE TABLE IF NOT EXISTS maosa_internal.cat_usuarios_importado (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                id_socio integer,
                socio character varying(255),
                id_estacion integer,
                estacion character varying(255),
                estatus boolean DEFAULT true NOT NULL,
                created_at timestamp without time zone,
                updated_at timestamp without time zone
            )
        SQL);

        // Índice para el filtro "estaciones activas" del select de usuarios
        DB::statement(<<<'SQL'
            CREATE INDEX IF NOT EXISTS idx_cat_usuarios_importado_estatus_estacion
                ON maosa_internal.cat_usuarios_importado (estatus, id_estacion)
        SQL);
    }

    public function down(): void
    {
        if (DB::getDriverName() !== 'pgsql') {
            return;
        }

        // No se elimina la tabla ni el schema: en Producción contienen datos
        // administrados por procesos externos. Solo se revierte el índice creado aquí.
        DB::statement('DROP INDEX IF EXISTS maosa_internal.idx_cat_usuarios_importado_estatus_estacion');
    }
};
