-- ============================================================================
-- Script DEV — Módulos: Gestión de Accesos, Estadísticas y Usuarios Inactivos
-- Base de datos: PostgreSQL
-- Equivalente raw SQL de las migraciones:
--   2026_07_06_000001_ensure_maosa_internal_cat_usuarios_importado
--   2026_07_06_000002_add_activity_indexes_for_user_tracking
-- Idempotente: puede ejecutarse varias veces sin error.
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1. Catálogo de socios/estaciones (fuente del select de estaciones activas)
--    En DEV normalmente no existe; se crea con la estructura mínima requerida.
-- ----------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS maosa_internal;

CREATE TABLE IF NOT EXISTS maosa_internal.cat_usuarios_importado (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_socio integer,
    socio character varying(255),
    id_estacion integer,
    estacion character varying(255),
    estatus boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);

CREATE INDEX IF NOT EXISTS idx_cat_usuarios_importado_estatus_estacion
    ON maosa_internal.cat_usuarios_importado (estatus, id_estacion);

-- Datos de ejemplo SOLO para desarrollo (no ejecutar en Prod)
INSERT INTO maosa_internal.cat_usuarios_importado (id_socio, socio, id_estacion, estacion, estatus, created_at, updated_at)
SELECT * FROM (VALUES
    (NULL::integer, NULL::varchar, 1001, 'Estación Centro',    true,  NOW(), NOW()),
    (NULL,          NULL,          1002, 'Estación Norte',     true,  NOW(), NOW()),
    (NULL,          NULL,          1003, 'Estación Sur',       true,  NOW(), NOW()),
    (NULL,          NULL,          1004, 'Estación Inactiva',  false, NOW(), NOW())
) AS seed(id_socio, socio, id_estacion, estacion, estatus, created_at, updated_at)
WHERE NOT EXISTS (SELECT 1 FROM maosa_internal.cat_usuarios_importado);

-- ----------------------------------------------------------------------------
-- 2. Índices de apoyo para estadísticas y detección de usuarios inactivos
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS user_sessions_user_id_created_at_index
    ON public.user_sessions (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS page_visits_user_id_created_at_index
    ON public.page_visits (user_id, created_at);

CREATE INDEX IF NOT EXISTS users_id_estacion_index
    ON public.users (id_estacion);

COMMIT;
